# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=http://localhost:5149

# Projects

# Create a project
POST {{host}}/api/projects
Content-Type: application/json
{
  "Name": "test project status delete 2",
  "Description": "my description.",
  "status": 1
}
###

# Get project by name
GET {{host}}/api/projects/byName/test4
###

# Get project by guid
GET {{host}}/api/projects/503f7c7e-fa87-4003-8015-b472549d1ef4
###

# Get all projects
GET {{host}}/api/projects/all
###

# Update project
PUT {{host}}/api/projects/
Content-Type: application/json
{
  "ProjectId": "503f7c7e-fa87-4003-8015-b472549d1ef4",
  "Name": "test updated",
  "Description": "description updated",
  "status": 9123
}
###

# Delete project
DELETE {{host}}/api/projects/a492d86f-eff0-424e-b786-ba41da835865
###

# Create a project status
POST {{host}}/api/projects/status/
Content-Type: application/json
{
  "name": "asd",
  "content": "a content."
}
###

# Get a project status
GET {{host}}/api/projects/status/mystatusproject
###

# Get all project status
GET {{host}}/api/projects/status/all
###

# Update a project status
PUT {{host}}/api/projects/status/
Content-Type: application/json
{
  "name": "asd",
  "content": "other content."
}
###

# Delete a project status
DELETE {{host}}/api/projects/status/asd
###

# Create a task
POST {{host}}/api/tasks
Content-Type: application/json
{
  "name": "test 2",
  "description": "this is a description.",
  "status": 3,
  "projectId": "33e716d1-bf32-48d3-b28e-15f94e3f2daf"
}
###

# Get task
GET {{host}}/api/tasks/39e841f6-ad7d-4a37-b1cd-9c232f1c0234
###

# Get task by name
GET {{host}}/api/tasks/byName/test
###

# Get all tasks
GET {{host}}/api/tasks/all
###

# Get all tasks by name
GET {{host}}/api/tasks/all/test
###

# Update a task
PUT {{host}}/api/tasks
Content-Type: application/json
{
  "taskId": "17ff3d19-47e9-459f-b01a-7838aa477839",
  "name": "test 2",
  "description": "a description.",
  "status": 2,
  "projectId": "68654605-7939-4d33-9ca2-146e8af0eda7"
}
###

# Delete a task
DELETE {{host}}/api/tasks/17ff3d19-47e9-459f-b01a-7838aa477839
###

# Create a note
POST {{host}}/api/notes
Content-Type: application/json
{
  "title": "test delete",
  "content": "A content.",
  "projectId": "33e716d1-bf32-48d3-b28e-15f94e3f2daf"
}
###

# Get note
GET {{host}}/api/notes/c9161ccd-991d-4423-a238-272f28ddc53e
###

# Get note by name
GET {{host}}/api/notes/byName/test.
###

# Get all notes
GET {{host}}/api/notes/all
###

# Update note
PUT {{host}}/api/notes
Content-Type: application/json
{
  "noteId": "f8f8880b-98cb-4537-b026-0b5f683f488d",
  "projectId": null
}
###

# Delete note
DELETE {{host}}/api/notes/ca99ebb1-7d0c-432a-9d3b-796b5132abe1
###

# Create a note tag
POST {{host}}/api/notes/tag
Content-Type: application/json
{
  "name": "My tag",
  "noteId": "ca99ebb1-7d0c-432a-9d3b-796b5132abe1"
}
###

# Get a note tag
GET {{host}}/api/notes/tag/18ff7332-98bc-48af-a95a-c6768519357a
###

# Get all note tags
GET {{host}}/api/notes/tag/all
###

# Update a note tag
PUT {{host}}/api/notes/tag
Content-Type: application/json
{
}
###

# Delete a note tag
DELETE {{host}}/api/notes/tag/
###
